### ISSUE TITLE
Possibility to use custom status

### ISSUE THREAD

**Issue by lukasoppermann** [hootlex/laravel-moderation#11]
Hey, very nice package. However, if this flow does not work with your process, you need to hack it.

What do you think about adding a possibility to add a custom status?

E.g. 

``` php
$post->setStatus('custom');

Post::all()->withStatus('custom');
```

Maybe the user can set those status and decide if they should be queried in strict mode or not.

You could even use magic methods to build `markCustom` methods. 

What do you think?

**Comment by stephane-monnot** [comment]
Good idea ! Actually, the differents status are hard coded, maybe need a little refactoring. 

Why not a `markAs` with a parameter ? Personally I prefer it, I don't like magic :wink:, and like idea completion.

**Comment by hootlex** [comment]
Hi @lukasoppermann, this is a very good idea.
The quickest way I can think of, is to use the config file to define the available statuses instead of the `Status` model.

What do you have in mind about magic methods?

**Comment by stephane-monnot** [comment]
@hootlex I think `$post->markNotForChildren()` (status = not_for_children), like the `markPending` method ( See [call magic method](http://php.net/manual/fr/language.oop5.overloading.php#object.call) ).

**Comment by lukasoppermann** [comment]
@stephane-monnot @hootlex exactly. But I would be fine with a `markAs()` method. It was a suggestion in case you wanted those methods.

Changing the status to be defined in a config file would make sense to me. This would even open it up to be stored in a database, retrieved and set as config variables, so it would make it very flexible!

I am just thinking that sometimes you need to create a business flow, e.g.

new Post() -> draft -> waiting for review ->  needs changes -> waiting for review -> ready for publication -> published / queued

Just as an example.

**Comment by stephane-monnot** [comment]
Maybe status are better in database, because:
 - we could use relationships with others tables 
 - if one day I want to remove a status, I will get an error if at least one post has been marked with this status (needed in foreign key constraint).

**Comment by lukasoppermann** [comment]
Hmm, maybe optionally? I am just thinking if you just have a published/unpublished case a database for just to status would be a bit of an overkill, would it not?

**Comment by stephane-monnot** [comment]
Yes, I agree, that's a bit overkill. As a first step, we should use config files.

**Comment by lukasoppermann** [comment]
Maybe we could require a "default" status or something so if the status that a model had is missing, it will be reset/interpreted as the default status? This could solve the problem you where describing correct?

**Comment by stephane-monnot** [comment]
Good idea ! 

@hootlex, what do you think ?

**Comment by hootlex** [comment]
@lukasoppermann @stephane-monnot I prefer to use config file to define the statuses. They can be defined within an array, which will contain an 'ID' and a 'name'. 

+1 for the default status fallback.
