### ISSUE TITLE
Adding events

### ISSUE THREAD

**Issue by lukasoppermann** [hootlex/laravel-moderation#13]
Thinking about status, etc. it might be a good idea to add events for when a status changes.

Think about an author getting a notification that his article is back from a review.
Or maybe it is published now, etc.

Using the laravel event system other parts of the app can easily subscribe to the `statusHasChanged` event and act on it, e.g. send out a notification, log something to a database, add something to a queue, ...

**Comment by stephane-monnot** [comment]
@lukasoppermann Very good idea !

**Comment by hootlex** [comment]
@lukasoppermann Yeah, I like this idea. I will start working on the suggested enhancements next week, but I don't promise anything. :smile:
