### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by AEK-BKF** [hootlex/laravel-moderation#30]
Hi, 
Thanks for this nice package !
Does this support L5.6 ?

Thanks

**Comment by stephane-monnot** [comment]
Some pull requests are here (#31 #29) for php7.2 support. 
In the package.json, I can see  "laravel/laravel": "5.*", so it's supposed to be compatible with Laravel 5.6.

**Comment by Michael-Brooks** [comment]
Any news on this? I would love to integrate this package, but I'm using 5.6

**Comment by stephane-monnot** [comment]
@hootlex ?

**Comment by hootlex** [comment]
Auto discovery & php 7.1/7.2 are supported in [v1.1.0](https://github.com/hootlex/laravel-moderation/releases/tag/v1.1.0) via https://github.com/hootlex/laravel-moderation/pull/31
