### ISSUE TITLE
Support for Laravel Nova

### ISSUE THREAD

**Issue by ginomessmer** [hootlex/laravel-moderation#34]
Is it possible to gather all entities within Laravel Nova while bypassing status moderation? I already disabled strict moderation, no luck though.

**Comment by mikebronner** [comment]
This is my work-around in the Resources class in Nova:
```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        $model = $query->getModel();

        if (method_exists($model, "withRejected")) {
            $query->withRejected();
        }

        return $query;
    }
```

**Comment by mikebronner** [comment]
Actually, this doesn't seem to be working anymore. @ginomessmer how did you overcome the issue?
