### ISSUE TITLE
2 suggestions ?

### ISSUE THREAD

**Issue by LonnyX** [hootlex/laravel-moderation#8]
Hi,

Great package, but I cannot use on my projects because you used the "status" attribute and I already use it almost everywhere with my own status.
- So maybe it's better to rename it to moderation_status or something else?
- And is this working with the update event? So when a post is updated, the moderator/admin have to "accept" the changes.

**Comment by hootlex** [comment]
Hello @LonnyX,

1. You can already change the default `status_column`. Check the [documentation](https://github.com/hootlex/laravel-moderation#global-configuration).
2. The Moderatable trait does not automatically update model's status on update but you can easily implement it by yourself by running `$model->markPending()` on update.

I hope I've got you covered.
