### ISSUE TITLE
laravel SoftDelete can't use

### ISSUE THREAD

**Issue by dongm2ez** [hootlex/laravel-moderation#9]
help me

How do use laravel softDelete with the laravel-moderation extension

is laravel 5.2

**Comment by dongm2ez** [comment]
this is my sql
 Activity::withAnyStatus()->where('id', 1)->delete();
but sql 
update `activity` set `moderated_at` = '2016-08-01 19:03:03', `updated_at` = '2016-08-01 19:03:03' where `id` = '1' and `activity`.`deleted_at` is null

**Comment by dongm2ez** [comment]
this use is normal
   use Moderatable,SoftDeletes;
but this use abnormal
   use SoftDeletes,Moderatable;

I don't know why，maybe u can talk me why. Thx

**Comment by dongm2ez** [comment]
I am a Chinese, English is poor, hope you can understand what I said, this is machine translation for me

**Comment by stephane-monnot** [comment]
Have you solved your problem ? If not, could you provide your error message ?

**Comment by hootlex** [comment]
Fixed in v1.0.9
